development:
  adapter: mysql2
  database: wallet_development
  pool: 5
  username: root

test:
  adapter: mysql2
  database: wallet_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  reconnect: true